# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon

from view.calendar import Ui_Form
from view.onplan import Ui_Onplan
from view.today import Ui_Today
from view.all import Ui_All


class Ui_panel(object):
    def setupUi(self, panel):
        panel.setObjectName("panel")
        panel.resize(1454, 925)
        self.pushButton_menu = QtWidgets.QPushButton(panel)
        self.pushButton_menu.setStyleSheet(u"QPushButton{\n"
                                           "	border:none\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "	padding-bottom:4px;\n"
                                           "}")
        self.pushButton_menu.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton_menu.setObjectName("pushButton_menu")
        icon = QIcon()
        icon.addFile(u"images/menu.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_menu.setIcon(icon)

        self.pushButton_user = QtWidgets.QPushButton(panel)
        self.pushButton_user.setObjectName(u"pushButton_user")
        self.pushButton_user.setStyleSheet(u"QPushButton{\n"
                                           "	border:none\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "	padding-bottom:4px;\n"
                                           "}")
        icon1 = QIcon()
        icon1.addFile(u"images/admin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_user.setIcon(icon1)
        self.pushButton_user.setGeometry(QtCore.QRect(40, 0, 40, 40))

        self.pushButton_min = QtWidgets.QPushButton(panel)
        self.pushButton_min.setObjectName(u"pushButton_min")
        self.pushButton_min.setStyleSheet(u"QPushButton{\n"
                                          "	border:none\n"
                                          "}\n"
                                          "QPushButton:hover{\n"
                                          "	padding-bottom:4px;\n"
                                          "}")
        icon2 = QIcon()
        icon2.addFile(u"images/minus-bold.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_min.setIcon(icon2)
        self.pushButton_min.setGeometry(QtCore.QRect(1373, 0, 40, 40))

        # self.pushButton_max = QtWidgets.QPushButton(panel)
        # self.pushButton_max.setObjectName(u"pushButton_max")
        # self.pushButton_max.setStyleSheet(u"QPushButton{\n"
        #                                 "	border:none\n"
        #                                 "}\n"
        #                                 "QPushButton:hover{\n"
        #                                 "	padding-bottom:4px;\n"
        #                                 "}\n"
        #                                 "")
        # icon3 = QIcon()
        # icon3.addFile(u"images/max.png", QSize(), QIcon.Normal, QIcon.Off)
        # self.pushButton_max.setIcon(icon3)
        # self.pushButton_max.setGeometry(QtCore.QRect(1353, 0, 40, 40))

        self.pushButton_close = QtWidgets.QPushButton(panel)
        self.pushButton_close.setObjectName(u"pushButton_close")
        self.pushButton_close.setStyleSheet(u"QPushButton{\n"
                                            "	border:none\n"
                                            "}\n"
                                            "QPushButton:hover{\n"
                                            "	padding-bottom:4px;\n"
                                            "}\n"
                                            "")
        icon4 = QIcon()
        icon4.addFile(u"images/close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_close.setIcon(icon4)
        self.pushButton_close.setGeometry(QtCore.QRect(1413, 0, 40, 40))

        icon5 = QIcon()
        icon5.addPixmap(QtGui.QPixmap("./images/add.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_add = QtWidgets.QPushButton(panel)
        self.pushButton_add.setGeometry(QtCore.QRect(75, 750, 110, 110))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_add.setIcon(icon5)
        self.pushButton_add.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_add.setStyleSheet('''QPushButton{
                                            border:none;
                                            background-color:transparent;
                    border-radius:5px;
                                            }
                                            QPushButton:hover
                  {
                    background-color:rgb(224,255,255);
                    border:none;
                    border-radius:55px;
                    color:white;
                  }
                                            ''')

        self.stackedWidget = QtWidgets.QStackedWidget(panel)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 40, 1304, 925))
        self.stackedWidget.setObjectName("stackedWidget")

        self.page_today = QtWidgets.QWidget()
        self.page_today.setObjectName("page_today")
        self.pageDecorate_today = Ui_Today()
        self.pageDecorate_today.setupUi(self.page_today)
        self.stackedWidget.addWidget(self.page_today)

        self.page_plan = QtWidgets.QWidget()
        self.page_plan.setObjectName("page_plan")
        self.pageDecorate_plan = Ui_Onplan()
        self.pageDecorate_plan.setupUi(self.page_plan)
        self.stackedWidget.addWidget(self.page_plan)

        self.page_all = QtWidgets.QWidget()
        self.page_all.setObjectName("page_plan")
        self.pageDecorate_all = Ui_All()
        self.pageDecorate_all.setupUi(self.page_all)
        self.stackedWidget.addWidget(self.page_all)

        self.page_ca = QtWidgets.QWidget()
        self.page_ca.setObjectName("page_ca")
        self.pageDecorate_ca = Ui_Form()
        self.pageDecorate_ca.setupUi(self.page_ca)
        self.stackedWidget.addWidget(self.page_ca)

        # self.page_data = QtWidgets.QWidget()
        # self.page_data.setObjectName("page_ca")
        # self.pageDecorate_data = Ui_Data()
        # self.pageDecorate_data.setupUi(self.page_data)
        # self.stackedWidget.addWidget(self.page_data)

        # self.page_ca.setStyleSheet(qss)
        # self.page_all.setStyleSheet(qss)
        # self.page_plan.setStyleSheet(qss)
        # self.page_today.setStyleSheet(qss)

        self.pushButton = QtWidgets.QPushButton(panel)
        self.pushButton.setGeometry(QtCore.QRect(3, 90, 250, 90))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(panel)
        self.pushButton_2.setGeometry(QtCore.QRect(3, 180, 250, 90))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(panel)
        self.pushButton_3.setGeometry(QtCore.QRect(3, 270, 250, 90))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(panel)
        self.pushButton_4.setGeometry(QtCore.QRect(3, 360, 250, 90))
        self.pushButton_4.setObjectName("pushButton_3")
        # self.pushButton_5 = QtWidgets.QPushButton(panel)
        # self.pushButton_5.setGeometry(QtCore.QRect(3, 450, 250, 90))
        # self.pushButton_5.setObjectName("pushButton_4")

        self.label = QtWidgets.QLabel(panel)
        self.label.setGeometry(QtCore.QRect(653, 0, 100, 50))
        self.label.setPixmap(QtGui.QPixmap("./images/to_do_37.png"))
        self.label.setText("")

        self.label_2 = QtWidgets.QLabel(panel)
        self.label_2.setGeometry(QtCore.QRect(695, 0, 150, 50))
        self.label_2.setPixmap(QtGui.QPixmap("./images/name_33.png"))
        self.label_2.setText("")

        self.retranslateUi(panel)
        QtCore.QMetaObject.connectSlotsByName(panel)

    def retranslateUi(self, panel):
        _translate = QtCore.QCoreApplication.translate
        panel.setWindowTitle(_translate("panel", "TO DO LIST"))
        self.pushButton.setText(_translate("panel", "我的一天"))
        self.pushButton_2.setText(_translate("panel", "计划内"))
        self.pushButton_3.setText(_translate("panel", "全部"))
        self.pushButton_4.setText(_translate("panel", "日历系统"))
        # self.pushButton_5.setText(_translate("panel", "数据统计"))
        # self.pushButton_add.setText(_translate("panel", "添加任务"))

    def change(self, index):
        self.stackedWidget.setCurrentIndex(index)
