# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from view.font import setFont
from view.frame import Frame
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont

css = "border-style:solid;border-top-width:0px;border-right-width:" + \
      "0px;border-bottom-width:1px;border-left-width:0px;"


class Ui_info(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 800)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 100, 500, 700))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("Account")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("Name")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("StudentId")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("PersonId")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label.setText("Account   :")
        self.label_2.setText("Name      :")
        self.label_3.setText("StudentId :")
        self.label_4.setText("PersonId  :")
        self.label.setFont(setFont(14))
        self.label_2.setFont(setFont(14))
        self.label_3.setFont(setFont(14))
        self.label_4.setFont(setFont(14))
        self.lineEdit.setFont(setFont(14))
        self.lineEdit_2.setFont(setFont(14))
        self.lineEdit_3.setFont(setFont(14))
        self.lineEdit_4.setFont(setFont(14))
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit_2.setAlignment(Qt.AlignCenter)
        self.lineEdit_3.setAlignment(Qt.AlignCenter)
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.lineEdit.setStyleSheet(css)
        self.lineEdit_2.setStyleSheet(css)
        self.lineEdit_3.setStyleSheet(css)
        self.lineEdit_4.setStyleSheet(css)
        self.lineEdit.setReadOnly(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4.setReadOnly(True)
        self.label.setStyleSheet("color:red")
        self.label_2.setStyleSheet("color:red")
        self.label_3.setStyleSheet("color:red")
        self.label_4.setStyleSheet("color:red")
        self.title = QtWidgets.QLabel(Form)
        self.title.setText("个人信息")
        font = QFont()
        font.setFamily("方正舒体")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.title.setFont(font)
        self.title.setAlignment(Qt.AlignCenter)
        self.title.setGeometry(QtCore.QRect(0, 0, 600, 200))
        self.title.setStyleSheet("color:red")

    # def set_con(self, personInfo):
    #     self.lineEdit.setText(personInfo['account'])
    #     self.lineEdit_2.setText(personInfo['name'])
    #     self.lineEdit_3.setText(personInfo['stu_num'])
    #     self.lineEdit_4.setText(personInfo['per_num'])
